services:
  - type: web
    name: libraryy
    env: python
    buildCommand: ./build.sh
    startCommand: python -m gunicorn --bind 0.0.0.0:$PORT --chdir libra libra.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DEBUG
        value: "TRUE"
      - key: DATABASE_URL
        value: "postgresql://admin_libra:RAEpt8V5RA5wM1DR4KmpYgDOHpoqpVso@dpg-d7kpu6df420s73ct6jc0-a/libra_db_2x7s"
      - key: SECRET_KEY
        value: "012cf9b14a47377f61701f5cba99da4d"
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        value: "batrkhan4.0@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "vchk xrtd itim qaxs"
      - key: EMAIL_USE_TLS
        value: "TRUE"
      - key: DEFAULT_FROM_EMAIL
        value: "Library <batrkhan4.0@gmail.com>"
      - key: USE_S3
        value: "TRUE"
      - key: B2_ACCESS_KEY_ID
        value: "0037e72242da82c0000000003"
      - key: B2_SECRET_ACCESS_KEY
        value: "K0032Y5LBXoWLvC/jVXBwpqGIBqvARg"
      - key: B2_BUCKET_NAME
        value: "libra-cloud"
      - key: B2_REGION
        value: "eu-central-003"
      - key: B2_ENDPOINT_URL
        value: "https://s3.eu-central-003.backblazeb2.com"
      - key: B2_MEDIA_PUBLIC_DOMAIN
        value: ""
      - key: B2_MEDIA_PUBLIC
        value: "True"

databases:
  - name: libraryy-db
    plan: free
    databaseName: libra_db
    user: libra_admin
