# Generated by Django 6.0.1 on 2026-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_alter_book_info_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books/pdf/%Y/%m/%d', verbose_name='PDF файл'),
        ),
    ]
