# Generated by Django 6.0.1 on 2026-03-26 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_book_info_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тип школы',
                'verbose_name_plural': 'Типы школ',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.AddField(
            model_name='book_info',
            name='target_group',
            field=models.CharField(blank=True, help_text='Например: ОДН-201, Преподаватели', max_length=100, verbose_name='Целевая группа'),
        ),
        migrations.AddField(
            model_name='book_info',
            name='school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='main.school_type', verbose_name='Тип школы'),
        ),
        migrations.AddField(
            model_name='book_info',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='main.specialization', verbose_name='Специализация'),
        ),
    ]
