# Generated by Django 6.0.1 on 2026-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bookreservationjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreservationjournal',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='bookreservationjournal',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя преподавателя'),
        ),
    ]
