# Generated by Django 6.0.1 on 2026-03-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_student_course_alter_student_homeroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Русский'), ('kk', 'Қазақша')], max_length=10, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
