"""
# Trigger reload
Django settings for libra project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(env_path: Path) -> None:
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


for candidate in (BASE_DIR.parent / '.env', BASE_DIR / '.env'):
    load_env_file(candidate)


def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name: str, default: str = '') -> list[str]:
    raw_value = os.getenv(name, default)
    return [item.strip() for item in raw_value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', '127.0.0.1,localhost,.onrender.com,.hoster.kz')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',

    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'libra.urls'

BOOTSTRAP4 = {
    'include_jquery': True,
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'libra.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use SQLite by default so the project works locally out of the box.
# Switch to PostgreSQL or MySQL/MariaDB explicitly with environment variables.
database_url = os.getenv('DATABASE_URL', '').strip()
database_scheme = urlparse(database_url).scheme.lower() if database_url else ''

USE_POSTGRES = env_bool('USE_POSTGRES', database_scheme in {'postgres', 'postgresql'})
USE_MYSQL = env_bool('USE_MYSQL', database_scheme in {'mysql', 'mariadb'})

if USE_MYSQL:
    if database_url and database_scheme in {'mysql', 'mariadb'}:
        parsed_db = urlparse(database_url)
        default_database = {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': parsed_db.path.lstrip('/') or os.getenv('MYSQL_DATABASE', os.getenv('DB_NAME', 'libra_db')),
            'USER': unquote(parsed_db.username or os.getenv('MYSQL_USER', os.getenv('DB_USER', 'root'))),
            'PASSWORD': unquote(parsed_db.password or os.getenv('MYSQL_PASSWORD', os.getenv('DB_PASSWORD', ''))),
            'HOST': parsed_db.hostname or os.getenv('MYSQL_HOST', os.getenv('DB_HOST', 'localhost')),
            'PORT': str(parsed_db.port or os.getenv('MYSQL_PORT', os.getenv('DB_PORT', '3306'))),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    else:
        default_database = {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('MYSQL_DATABASE', os.getenv('DB_NAME', 'libra_db')),
            'USER': os.getenv('MYSQL_USER', os.getenv('DB_USER', 'root')),
            'PASSWORD': os.getenv('MYSQL_PASSWORD', os.getenv('DB_PASSWORD', '')),
            'HOST': os.getenv('MYSQL_HOST', os.getenv('DB_HOST', 'localhost')),
            'PORT': os.getenv('MYSQL_PORT', os.getenv('DB_PORT', '3306')),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    DATABASES = {'default': default_database}
elif USE_POSTGRES:
    if database_url and database_scheme in {'postgres', 'postgresql'}:
        parsed_db = urlparse(database_url)
        db_host = parsed_db.hostname or os.getenv('POSTGRES_HOST', os.getenv('PGHOST', os.getenv('DB_HOST', 'localhost')))
        db_sslmode = os.getenv('POSTGRES_SSLMODE', os.getenv('PGSSLMODE', 'require' if db_host.endswith('render.com') else 'prefer'))
        default_database = {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': parsed_db.path.lstrip('/') or os.getenv('POSTGRES_DB', os.getenv('PGDATABASE', os.getenv('DB_NAME', 'libra_db'))),
            'USER': unquote(parsed_db.username or os.getenv('POSTGRES_USER', os.getenv('PGUSER', os.getenv('DB_USER', 'libra_admin')))),
            'PASSWORD': unquote(parsed_db.password or os.getenv('POSTGRES_PASSWORD', os.getenv('PGPASSWORD', os.getenv('DB_PASSWORD', 'password')))),
            'HOST': db_host,
            'PORT': str(parsed_db.port or os.getenv('POSTGRES_PORT', os.getenv('PGPORT', os.getenv('DB_PORT', '5432')))),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
        }
        if db_sslmode:
            default_database['OPTIONS'] = {'sslmode': db_sslmode}
    else:
        default_database = {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.getenv('POSTGRES_DB', os.getenv('PGDATABASE', os.getenv('DB_NAME', 'libra_db'))),
            'USER': os.getenv('POSTGRES_USER', os.getenv('PGUSER', os.getenv('DB_USER', 'libra_admin'))),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', os.getenv('PGPASSWORD', os.getenv('DB_PASSWORD', 'password'))),
            'HOST': os.getenv('POSTGRES_HOST', os.getenv('PGHOST', os.getenv('DB_HOST', 'localhost'))),
            'PORT': os.getenv('POSTGRES_PORT', os.getenv('PGPORT', os.getenv('DB_PORT', '5432'))),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
        }

    DATABASES = {'default': default_database}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    'main.backends.EmailOrUsernameModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('ru', 'Русский'),
    ('kk', 'Қазақша'),
    ('en', 'English'),
]

# Email settings for registration and password reset
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Library <no-reply@library.local>')

# If no SMTP server is configured, stay in console mode so the app doesn't fail.
if not EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'
MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'en'
MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'kk'

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'main', 'static'),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

USE_S3 = env_bool('USE_S3', False)

b2_access_key = os.getenv('B2_ACCESS_KEY_ID', '').strip()
b2_secret_key = os.getenv('B2_SECRET_ACCESS_KEY', '').strip()
b2_bucket = os.getenv('B2_BUCKET_NAME', '').strip()
b2_endpoint = os.getenv('B2_ENDPOINT_URL', '').strip()
b2_region = os.getenv('B2_REGION', '').strip()
b2_public_domain = os.getenv('B2_MEDIA_PUBLIC_DOMAIN', '').strip()

if USE_S3:
    # Fall back to local media storage if required B2 values are not configured.
    required_b2_values = {
        'B2_ACCESS_KEY_ID': b2_access_key,
        'B2_SECRET_ACCESS_KEY': b2_secret_key,
        'B2_BUCKET_NAME': b2_bucket,
        'B2_ENDPOINT_URL': b2_endpoint,
    }
    missing_b2_values = [name for name, value in required_b2_values.items() if not value]
    if missing_b2_values:
        USE_S3 = False
        print(
            'USE_S3 is enabled, but required B2 variables are missing: '
            f"{', '.join(missing_b2_values)}. Falling back to local media storage."
        )

if USE_S3:
    b2_public = env_bool('B2_MEDIA_PUBLIC', True)
    b2_custom_domain = b2_public_domain

    AWS_ACCESS_KEY_ID = b2_access_key
    AWS_SECRET_ACCESS_KEY = b2_secret_key
    AWS_STORAGE_BUCKET_NAME = b2_bucket
    AWS_S3_REGION_NAME = b2_region
    AWS_S3_ENDPOINT_URL = b2_endpoint
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = not b2_public
    AWS_S3_FILE_OVERWRITE = False

    if b2_custom_domain:
        AWS_S3_CUSTOM_DOMAIN = b2_custom_domain

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

    if b2_custom_domain:
        MEDIA_URL = f"https://{b2_custom_domain}/"
    elif b2_endpoint and b2_bucket:
        MEDIA_URL = f"{b2_endpoint.rstrip('/')}/{b2_bucket}/"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
