# Generated by Django 6.0.1 on 2026-01-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookloan_reservation_alter_book_info_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='available_copies',
            field=models.PositiveIntegerField(default=1, verbose_name='Доступно экземпляров'),
        ),
        migrations.AddField(
            model_name='book_info',
            name='total_copies',
            field=models.PositiveIntegerField(default=1, verbose_name='Всего экземпляров'),
        ),
    ]
