# Generated by Django 6.0.1 on 2026-03-26 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_school_type_specialization_book_info_target_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReservationJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='Имя студента')),
                ('group_name', models.CharField(max_length=100, verbose_name='Группа')),
                ('reservation_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время бронирования')),
                ('expiration_date', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('status', models.CharField(choices=[('reserved', 'Зарезервирована'), ('returned', 'Возвращена')], default='reserved', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book_info', verbose_name='Книга')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Бронь в журнале',
                'verbose_name_plural': 'Брони в журнале',
                'ordering': ['-reservation_datetime'],
            },
        ),
    ]
