# Generated by Django 6.0.1 on 2026-03-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bookreservationjournal_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_books',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='main.book_info', verbose_name='Сохранённые книги'),
        ),
        migrations.AlterField(
            model_name='bookreservationjournal',
            name='status',
            field=models.CharField(choices=[('reserved', 'Зарезервирована'), ('returned', 'Возвращена'), ('expired', 'Просрочена')], default='reserved', max_length=20, verbose_name='Статус'),
        ),
    ]
