# Generated by Django 6.0.1 on 2026-03-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_book_info_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='Номер студенческого билета')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='Группа')),
                ('homeroom_teacher', models.CharField(blank=True, max_length=200, verbose_name='Классная руководительница')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['student_id'],
            },
        ),
        migrations.RemoveField(
            model_name='book_info',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book_info',
            name='target_group',
        ),
        migrations.AlterField(
            model_name='book_info',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақша'), ('en', 'English')], default='ru', max_length=2, verbose_name='Язык'),
        ),
    ]
