# Generated by Django 6.0.1 on 2026-03-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_student_remove_book_info_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=100, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='homeroom_teacher',
            field=models.CharField(blank=True, max_length=200, verbose_name='Руководитель'),
        ),
    ]
