# Generated by Django 6.0.1 on 2026-05-25 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_bookreservationjournal_returned_late'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'ID должен состоять из 4 цифр.')], verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Кафедра/отдел')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['teacher_id'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='person_type',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель')], default='student', max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'ID должен состоять из 4 цифр.')], verbose_name='ID преподавателя'),
        ),
    ]
