# Generated by Django 6.0.1 on 2026-05-25 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_teacher_profile_person_type_profile_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=4, unique=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='Группа')),
                ('course', models.CharField(blank=True, max_length=100, verbose_name='Курс')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специальность')),
                ('language', models.CharField(blank=True, choices=[('ru', 'Русский'), ('kk', 'Қазақша')], max_length=10, verbose_name='Язык')),
                ('homeroom_teacher', models.CharField(blank=True, max_length=200, verbose_name='Руководитель')),
                ('original_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления в основной список')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата удаления из основного списка')),
            ],
            options={
                'verbose_name': 'Резервный студент',
                'verbose_name_plural': 'Резервные студенты',
                'ordering': ['-deleted_at', 'student_id'],
            },
        ),
    ]
